stages:
  - install
  - build
  - publish

cache:
  paths:
    - node_modules/

Install:
  stage: install
  tags:
    - npm
  script: yarn install --prefer-offline

Build:
  stage: build
  tags:
    - npm
  script: yarn build
  artifacts:
    paths:
      - dist/
      - types/

Deploy:
  only:
    - /^v.*$/
  except:
    - branches
  stage: publish
  tags:
    - npm
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish

